import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Screen/navbar";
import { Footer } from "@/Screen/footer";
import HeroPage from "@/Screen/hero";
import Standard from "@/Screen/standard";
import BehindUs from "@/Screen/behind";
import Values from "@/Screen/values";
import Thrive from "@/Screen/thrive";
import Journey from "@/Screen/journey";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <HeroPage/>
        <Standard/>
        <BehindUs/>
        <Values/>
        <Thrive/>
        <Journey/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
